# Group by

#### Iterating over each row is not efficient (not pandorable)

### Use group by -> returns a DataFrame 'groupby' obj

In [6]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('census.csv')

In [31]:
df = df[df['SUMLEV'] == 50]

### Loop vs Groupby

In [7]:
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME'] == state).dropna()['CENSUS2010POP'])

In [8]:
for group, frame in df.groupby('STNAME'):
    avg = np.average(frame['CENSUS2010POP'])

### Usually groupby on one or more columns. We can also groupby on a function

#### Below is an example of using groupby. 
#### This splits the df into segments according to the funciton
#### Acts as a "light-hashing" function and distribute tasks across multiple workers.
##### workers -> cores (processor), disk (DB), nodes (super computer), etc

In [11]:
df2 = df.set_index('STNAME')

def fun(item):
    if item[0] < 'M':
        return 0
    if item[0] < 'Q':
        return 1
    return 2

for group, frame in df2.groupby(fun):
    print('There are ' + str(len(frame)) + ' records in  group' + str(group) + ' for processing.')

There are 1177 records in  group0 for processing.
There are 1134 records in  group1 for processing.
There are 831 records in  group2 for processing.

#### Using agg function for groupby obj to aggregate. agg takes in a dict in the form of {column to process : function to use for processing}

In [18]:
df.groupby('STNAME').agg({'CENSUS2010POP' : np.average, 'ESTIMATESBASE2010' : np.min})

                      CENSUS2010POP  ESTIMATESBASE2010
STNAME
Alabama                71339.343284               9045
Alaska                 24490.724138                662
Arizona               426134.466667               8437
Arkansas               38878.906667               5368
California            642309.586207               1175
Colorado               78581.187500                699
Connecticut           446762.125000             118434
Delaware              299311.333333             162349
District of Columbia  601723.000000             601767
Florida               280616.567164               8365
Georgia                60928.635220               1717
Hawaii                272060.200000                 90
Idaho                  35626.863636                982
Illinois              125790.509804               4320
Indiana                70476.108696               6128
Iowa                   30771.262626               4029
Kansas                 27172.552381               1247
Kentucky               36161.391667               2282
Louisiana              70833.937500               5252
Maine                  83022.562500              17535
Maryland              240564.666667              20197
Massachusetts         467687.785714              10172
Michigan              119080.000000               2156
Minnesota              60964.655172               3558
Mississippi            36186.548780               1406
Missouri               52077.626087               2171
Montana                17668.125000                494
Nebraska               19638.075269                460
Nevada                158855.941176                784
New Hampshire         131647.000000              33052
New Jersey            418661.619048              66083
New Mexico             62399.363636                695
New York              312550.032258               4843
North Carolina         95354.830000               4407
North Dakota           12690.396226                727
Ohio                  131096.636364              13435
Oklahoma               48718.844156               2475
Oregon                106418.722222               1441
Pennsylvania          189587.746269               5085
Rhode Island          210513.400000              49875
South Carolina        100551.391304              10233
South Dakota           12336.060606               1006
Tennessee              66801.105263               5077
Texas                  98998.271654                 82
Utah                   95306.379310               1061
Vermont                44695.785714               6306
Virginia               60111.293233               2319
Washington            172424.102564               2266
West Virginia          33690.800000               5717
Wisconsin              78985.916667               4232
Wyoming                24505.478261               2484

#### Groupby example with lambda function in apply.

In [23]:
df.groupby('STNAME').apply(lambda df, a, b: sum(df[a] * df[b]), 'RNETMIG2014', 'RNETMIG2015')

STNAME
Alabama                  3105.689539
Alaska                   5956.228409
Arizona                  1790.650867
Arkansas                 5209.375722
California               1274.447200
Colorado                 4150.673027
Connecticut               110.307146
Delaware                  518.406134
District of Columbia      104.179527
Florida                 18191.301588
Georgia                 12361.318379
Hawaii                    200.072397
Idaho                    3078.758298
Illinois                 4804.842214
Indiana                  1759.873291
Iowa                     1761.474213
Kansas                   5227.838473
Kentucky                 2882.495683
Louisiana                4040.062852
Maine                     202.889271
Maryland                  194.926205
Massachusetts             194.843516
Michigan                  330.050111
Minnesota                1335.114966
Mississippi              6303.758380
Missouri                 2687.201124
Montana                  3985.720018
Nebraska                 1913.441601
Nevada                   1951.755521
New Hampshire             100.322714
New Jersey                208.016570
New Mexico               4517.090474
New York                 1660.072248
North Carolina           7553.359091
North Dakota            32684.871382
Ohio                     1188.679210
Oklahoma                 3801.084864
Oregon                   3138.954600
Pennsylvania              944.923030
Rhode Island                0.628898
South Carolina           5367.639154
South Dakota             4329.950322
Tennessee                4290.832952
Texas                  -23798.798446
Utah                     3505.869881
Vermont                    10.029685
Virginia                 2918.695595
Washington               2073.377771
West Virginia            1504.754868
Wisconsin                  47.425931
Wyoming                   886.634175
dtype: float64

#### Passing in a dict to the apply function has 2 cases:
##### 1. Identify columns to run a function on
##### 2. Name an output column if there are multiple functions to be run

In [25]:
# DataFrame Groupby -> multiple columns selection yields a DF
print(type(df.groupby(level=0)['POPESTIMATE2010', 'POPESTIMATE2010']))

# Series Groupby -> Single column yields a Series
print(type(df.groupby(level=0)['POPESTIMATE2010']))

<class 'pandas.core.groupby.DataFrameGroupBy'>
<class 'pandas.core.groupby.SeriesGroupBy'>

In [32]:
# using a dict on Series for aggregation is deprecated. This will be removed.
(df.set_index('STNAME').groupby(level=0)['CENSUS2010POP']
   .agg({'avg' : np.average, 'sum' : np.sum}))

/Users/elli/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  app.launch_new_instance()

                                avg       sum
STNAME
Alabama                71339.343284   4779736
Alaska                 24490.724138    710231
Arizona               426134.466667   6392017
Arkansas               38878.906667   2915918
California            642309.586207  37253956
Colorado               78581.187500   5029196
Connecticut           446762.125000   3574097
Delaware              299311.333333    897934
District of Columbia  601723.000000    601723
Florida               280616.567164  18801310
Georgia                60928.635220   9687653
Hawaii                272060.200000   1360301
Idaho                  35626.863636   1567582
Illinois              125790.509804  12830632
Indiana                70476.108696   6483802
Iowa                   30771.262626   3046355
Kansas                 27172.552381   2853118
Kentucky               36161.391667   4339367
Louisiana              70833.937500   4533372
Maine                  83022.562500   1328361
Maryland              240564.666667   5773552
Massachusetts         467687.785714   6547629
Michigan              119080.000000   9883640
Minnesota              60964.655172   5303925
Mississippi            36186.548780   2967297
Missouri               52077.626087   5988927
Montana                17668.125000    989415
Nebraska               19638.075269   1826341
Nevada                158855.941176   2700551
New Hampshire         131647.000000   1316470
New Jersey            418661.619048   8791894
New Mexico             62399.363636   2059179
New York              312550.032258  19378102
North Carolina         95354.830000   9535483
North Dakota           12690.396226    672591
Ohio                  131096.636364  11536504
Oklahoma               48718.844156   3751351
Oregon                106418.722222   3831074
Pennsylvania          189587.746269  12702379
Rhode Island          210513.400000   1052567
South Carolina        100551.391304   4625364
South Dakota           12336.060606    814180
Tennessee              66801.105263   6346105
Texas                  98998.271654  25145561
Utah                   95306.379310   2763885
Vermont                44695.785714    625741
Virginia               60111.293233   7994802
Washington            172424.102564   6724540
West Virginia          33690.800000   1852994
Wisconsin              78985.916667   5686986
Wyoming                24505.478261    563626

In [36]:
df.groupby('STNAME').agg({'CENSUS2010POP': np.average})

                      CENSUS2010POP
STNAME
Alabama                71339.343284
Alaska                 24490.724138
Arizona               426134.466667
Arkansas               38878.906667
California            642309.586207
Colorado               78581.187500
Connecticut           446762.125000
Delaware              299311.333333
District of Columbia  601723.000000
Florida               280616.567164
Georgia                60928.635220
Hawaii                272060.200000
Idaho                  35626.863636
Illinois              125790.509804
Indiana                70476.108696
Iowa                   30771.262626
Kansas                 27172.552381
Kentucky               36161.391667
Louisiana              70833.937500
Maine                  83022.562500
Maryland              240564.666667
Massachusetts         467687.785714
Michigan              119080.000000
Minnesota              60964.655172
Mississippi            36186.548780
Missouri               52077.626087
Montana                17668.125000
Nebraska               19638.075269
Nevada                158855.941176
New Hampshire         131647.000000
New Jersey            418661.619048
New Mexico             62399.363636
New York              312550.032258
North Carolina         95354.830000
North Dakota           12690.396226
Ohio                  131096.636364
Oklahoma               48718.844156
Oregon                106418.722222
Pennsylvania          189587.746269
Rhode Island          210513.400000
South Carolina        100551.391304
South Dakota           12336.060606
Tennessee              66801.105263
Texas                  98998.271654
Utah                   95306.379310
Vermont                44695.785714
Virginia               60111.293233
Washington            172424.102564
West Virginia          33690.800000
Wisconsin              78985.916667
Wyoming                24505.478261

In [38]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']
    .agg({'avg': np.average, 'sum': np.sum}))

/Users/elli/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/groupby.py:4036: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

                                 avg                             sum  \
                     POPESTIMATE2010 POPESTIMATE2011 POPESTIMATE2010
STNAME
Alabama                 71420.313433    71658.328358         4785161
Alaska                  24621.413793    24921.379310          714021
Arizona                427213.866667   431248.800000         6408208
Arkansas                38965.253333    39180.506667         2922394
California             643691.017241   650000.586207        37334079
Colorado                78878.968750    79991.875000         5048254
Connecticut            447464.625000   448719.875000         3579717
Delaware               299930.333333   302638.666667          899791
District of Columbia   605126.000000   620472.000000          605126
Florida                281341.641791   285157.208955        18849890
Georgia                 61090.905660    61712.452830         9713454
Hawaii                 272796.000000   275645.400000         1363980
Idaho                   35704.227273    36003.045455         1570986
Illinois               125894.598039   126096.882353        12841249
Indiana                 70549.891304    70835.271739         6490590
Iowa                    30815.090909    30963.525253         3050694
Kansas                  27226.895238    27332.542857         2858824
Kentucky                36232.808333    36399.016667         4347937
Louisiana               71014.859375    71490.328125         4544951
Maine                   82980.937500    83016.062500         1327695
Maryland               241183.708333   243507.125000         5788409
Massachusetts          468931.142857   472271.214286         6565036
Michigan               119004.445783   118995.048193         9877369
Minnesota               61044.862069    61472.632184         5310903
Mississippi             36223.365854    36317.060976         2970316
Missouri                52139.582609    52265.973913         5996052
Montana                 17690.053571    17816.892857          990643
Nebraska                19677.688172    19810.569892         1830025
Nevada                 159025.882353   159930.529412         2703440
New Hampshire          131670.800000   131834.400000         1316708
New Jersey             419232.428571   421092.095238         8803881
New Mexico              62567.909091    62976.545455         2064741
New York               312950.322581   314890.354839        19402920
North Carolina          95589.790000    96510.250000         9558979
North Dakota            12726.981132    12930.679245          674530
Ohio                   131145.068182   131198.204545        11540766
Oklahoma                48825.922078    49176.961039         3759596
Oregon                 106610.333333   107458.583333         3837972
Pennsylvania           189731.552239   190226.895522        12712014
Rhode Island           210643.800000   210371.200000         1053219
South Carolina         100780.304348   101581.152174         4635894
South Dakota            12368.166667    12489.227273          816299
Tennessee               66911.421053    67351.663158         6356585
Texas                   99387.255906   101001.826772        25244363
Utah                    95704.344828    97118.620690         2775426
Vermont                 44713.142857    44763.357143          625984
Virginia                60344.263158    60983.330827         8025787
Washington             172898.974359   174954.589744         6743060
West Virginia           33713.181818    33726.327273         1854225
Wisconsin               79030.611111    79301.666667         5690204
Wyoming                 24544.173913    24685.565217          564516


                     POPESTIMATE2011
STNAME
Alabama                      4801108
Alaska                        722720
Arizona                      6468732
Arkansas                     2938538
California                  37700034
Colorado                     5119480
Connecticut                  3589759
Delaware                      907916
District of Columbia          620472
Florida                     19105533
Georgia                      9812280
Hawaii                       1378227
Idaho                        1584134
Illinois                    12861882
Indiana                      6516845
Iowa                         3065389
Kansas                       2869917
Kentucky                     4367882
Louisiana                    4575381
Maine                        1328257
Maryland                     5844171
Massachusetts                6611797
Michigan                     9876589
Minnesota                    5348119
Mississippi                  2977999
Missouri                     6010587
Montana                       997746
Nebraska                     1842383
Nevada                       2718819
New Hampshire                1318344
New Jersey                   8842934
New Mexico                   2078226
New York                    19523202
North Carolina               9651025
North Dakota                  685326
Ohio                        11545442
Oklahoma                     3786626
Oregon                       3868509
Pennsylvania                12745202
Rhode Island                 1051856
South Carolina               4672733
South Dakota                  824289
Tennessee                    6398408
Texas                       25654464
Utah                         2816440
Vermont                       626687
Virginia                     8110783
Washington                   6823229
West Virginia                1854948
Wisconsin                    5709720
Wyoming                       567768

#### If keys in the dict matches up with column names, the aggregate function will perform the given functions (values) on the specified columns directly without creating new columns

In [40]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']
    .agg({'POPESTIMATE2010': np.average, 'POPESTIMATE2011': np.sum}))

                      POPESTIMATE2010  POPESTIMATE2011
STNAME
Alabama                  71420.313433          4801108
Alaska                   24621.413793           722720
Arizona                 427213.866667          6468732
Arkansas                 38965.253333          2938538
California              643691.017241         37700034
Colorado                 78878.968750          5119480
Connecticut             447464.625000          3589759
Delaware                299930.333333           907916
District of Columbia    605126.000000           620472
Florida                 281341.641791         19105533
Georgia                  61090.905660          9812280
Hawaii                  272796.000000          1378227
Idaho                    35704.227273          1584134
Illinois                125894.598039         12861882
Indiana                  70549.891304          6516845
Iowa                     30815.090909          3065389
Kansas                   27226.895238          2869917
Kentucky                 36232.808333          4367882
Louisiana                71014.859375          4575381
Maine                    82980.937500          1328257
Maryland                241183.708333          5844171
Massachusetts           468931.142857          6611797
Michigan                119004.445783          9876589
Minnesota                61044.862069          5348119
Mississippi              36223.365854          2977999
Missouri                 52139.582609          6010587
Montana                  17690.053571           997746
Nebraska                 19677.688172          1842383
Nevada                  159025.882353          2718819
New Hampshire           131670.800000          1318344
New Jersey              419232.428571          8842934
New Mexico               62567.909091          2078226
New York                312950.322581         19523202
North Carolina           95589.790000          9651025
North Dakota             12726.981132           685326
Ohio                    131145.068182         11545442
Oklahoma                 48825.922078          3786626
Oregon                  106610.333333          3868509
Pennsylvania            189731.552239         12745202
Rhode Island            210643.800000          1051856
South Carolina          100780.304348          4672733
South Dakota             12368.166667           824289
Tennessee                66911.421053          6398408
Texas                    99387.255906         25654464
Utah                     95704.344828          2816440
Vermont                  44713.142857           626687
Virginia                 60344.263158          8110783
Washington              172898.974359          6823229
West Virginia            33713.181818          1854948
Wisconsin                79030.611111          5709720
Wyoming                  24544.173913           567768